### PR TITLE
added mayhem support

### PR DESCRIPTION
**Pull request by matl4c**

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
Any reason for the updated CONTRIBUTORS.svg? This won't be reflected on upstream unless it's merged to upstream (which may not happen in the short term). Please make the requested changes.

**Comment by matl4c** [comment]
> Any reason for the updated CONTRIBUTORS.svg? This won't be reflected on upstream unless it's merged to upstream (which may not happen in the short term). Please make the requested changes.

This was done automatically by the projects workflows

**Comment by xansec** [comment]
Ok. Can you pull from the latest upstream to make sure it matches? I have rebased this fork with upstream so there should be no difference between your copy of `CONTRIBUTORS.svg` and this fork's. 
Also, please restore the deleted workflow.

**Comment by matl4c** [comment]
I likely won't get to this until Friday, I have exams. Either way I will resolve it soon. Thank you for the help!

**Comment by xansec** [comment]
I went ahead and manually applied the changes here https://github.com/mayhemheroes/scant3r/commit/2689be79c168164725a9f8e872b74ab74a5faece

You should receive confirmation that the submission was processed very soon. Thanks!

**Pull request closed without merging**
